Django_/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Django_ import settings
from users.views import IndexView

urlpatterns = [
                  # 首页直接进行跳转
                  path('', IndexView.as_view(), name='index'),
                  path('admin/', admin.site.urls),
                  path('captcha/', include('captcha.urls')),
                  path('ckeditor/', include('ckeditor_uploader.urls')),
                  # version more better I have last version
                  # path('ueditor/', include('DjangoUeditor.urls')),
                  # path('xadmin/', xadmin.site.urls),
                  path('users/', include(('users.urls', 'users'), namespace='users')),
                  path('courses/', include(('courses.urls', 'courses'), namespace='courses')),
                  path('orgs/', include(('orgs.urls', 'orgs'), namespace='orgs')),
                  path('operations/', include(('operations.urls', 'operations'), namespace='operations')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'users.views.handle_404'
handler500 = 'users.views.handler_500'

apps/courses/urls.py
from django.urls import path, re_path

from .views import CourseListView, CourseDetailView, CourseVideoView, CourseCommentView

urlpatterns = [
    path('course_list/', CourseListView.as_view(), name='course_list'),
    re_path('course_detail/(\\d+)', CourseDetailView.as_view(), name='course_detail'),
    re_path('course_video/(\\d+)', CourseVideoView.as_view(), name='course_video'),
    re_path('course_comment/(\\d+)', CourseCommentView.as_view(), name='course_comment'),
]

apps/operations/urls.py
from django.urls import path

from .views import UserAskView, UserLoveView, UserDeleteLoveView, UserCommentView, UserMessageView

urlpatterns = [
    path('user_ask/', UserAskView.as_view(), name='user_ask'),

    path('user_love/', UserLoveView.as_view(), name='user_love'),
    path('user_delete_love/', UserDeleteLoveView.as_view(), name='user_delete_love'),

    path('user_comment/', UserCommentView.as_view(), name='user_comment'),
    path('user_message/', UserMessageView.as_view(), name='user_message'),
]

apps/orgs/urls.py
from django.urls import path, re_path

from .views import OrgListView, OrgDetailView, OrgDetailCourseView, OrgDetailDescView, OrgDetailTeachersView, \
    TeacherListView, TeacherDetailView

urlpatterns = [
    path('org_list/', OrgListView.as_view(), name='org_list'),
    re_path('org_detail/(\\d+)', OrgDetailView.as_view(), name='org_detail'),
    re_path('org_detail_course/(\\d+)', OrgDetailCourseView.as_view(), name='org_detail_course'),
    re_path('org_detail_desc/(\\d+)', OrgDetailDescView.as_view(), name='org_detail_desc'),
    re_path('org_detail_teachers/(\\d+)', OrgDetailTeachersView.as_view(), name='org_detail_teachers'),
    # teacher
    path('teacher_list/', TeacherListView.as_view(), name='teacher_list'),
    re_path('teacher_detail/(\\d+)', TeacherDetailView.as_view(), name='teacher_detail'),
]

apps/users/urls.py
from django.urls import path, re_path

from .views import UserRegisterView, UserLoginView, UserLogoutView, UserActiveView, UserForgetView, UserResetView, \
    UserInfoView, UserChangeImageView, UserChangeInfoView, UserChangeEmailView, UserRestEmailView, UserCourseView, \
    UserLoveOrgView, UserLoveCourseView, UserLoveTeacherView, UserMessageView

urlpatterns = [
    # name 必须是 'xxx'
    path('user_register/', UserRegisterView.as_view(), name='user_register'),
    path('user_login/', UserLoginView.as_view(), name='user_login'),
    path('user_logout/', UserLogoutView.as_view(), name='user_logout'),
    # 如果要使用正则表达式 需要使用re_path
    re_path('user_active/(\\w+)/', UserActiveView.as_view(), name='user_active'),

    path('user_forget/', UserForgetView.as_view(), name='user_forget'),
    re_path('user_reset/(\\w+)/', UserResetView.as_view(), name='user_reset'),

    path('user_info/', UserInfoView.as_view(), name='user_info'),
    path('user_change_image/', UserChangeImageView.as_view(), name='user_change_image'),
    path('user_change_info/', UserChangeInfoView.as_view(), name='user_change_info'),
    path('user_change_email/', UserChangeEmailView.as_view(), name='user_change_email'),
    path('user_rest_email/', UserRestEmailView.as_view(), name='user_rest_email'),

    path('user_course/', UserCourseView.as_view(), name='user_course'),
    path('user_love_org/', UserLoveOrgView.as_view(), name='user_love_org'),
    path('user_love_teacher/', UserLoveTeacherView.as_view(), name='user_love_teacher'),
    path('user_love_course/', UserLoveCourseView.as_view(), name='user_love_course'),

    path('user_message/', UserMessageView.as_view(), name='user_message'),
]

apps/courses/models.py
from datetime import datetime

from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models

from orgs.models import OrgInfo, TeacherInfo


# Create your models here.
class CourseInfo(models.Model):
    image = models.ImageField(upload_to='course/', verbose_name='课程封面', max_length=200)
    name = models.CharField(max_length=20, verbose_name='课程名称')
    is_banner = models.BooleanField(default=False, verbose_name='是否轮播')

    study_time = models.IntegerField(default=0, verbose_name='学习时长')
    study_num = models.IntegerField(default=0, verbose_name='学习人数')
    level = models.CharField(choices=(('gj', '高级'), ('zj', '中级'), ('cj', '初级')), default='cj', max_length=3,
                             verbose_name='难度')

    love_num = models.IntegerField(default=0, verbose_name='收藏数')
    click_num = models.IntegerField(default=0, verbose_name='访问量')

    desc = models.CharField(verbose_name='课程简介', max_length=200)
    # detail = models.TextField(verbose_name='课程详情')
    detail = RichTextUploadingField(default='', verbose_name='课程详情')

    category = models.CharField(choices=(('qd', '前端开发'), ('hd', '后端开发')), default='hd',
                                verbose_name='课程类别', max_length=20)

    course_notice = models.CharField(max_length=200, verbose_name='课程公告')
    course_need = models.CharField(max_length=200, verbose_name='课程须知')
    teacher_tell = models.CharField(max_length=200, verbose_name='老师告诉')
    org_info = models.ForeignKey(OrgInfo, verbose_name='所属机构', on_delete=models.CASCADE)
    teacher_info = models.ForeignKey(TeacherInfo, verbose_name='所属讲师', on_delete=models.CASCADE)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '课程信息'
        verbose_name_plural = verbose_name


# 章节信息
class ChapterInfo(models.Model):
    name = models.CharField(max_length=20, verbose_name='章节名称')
    course_info = models.ForeignKey(CourseInfo, verbose_name='所属课程', on_delete=models.CASCADE)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '章节信息'
        verbose_name_plural = verbose_name


class VideoInfo(models.Model):
    name = models.CharField(max_length=20, verbose_name='视频名称')
    study_time = models.IntegerField(default=0, verbose_name='视频时长')
    url = models.URLField(default='https://www.baidu.com', verbose_name='视频链接', max_length=200)
    chapter_info = models.ForeignKey(ChapterInfo, verbose_name='所属章节', on_delete=models.CASCADE)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '视频信息'
        verbose_name_plural = verbose_name


class SourceInfo(models.Model):
    name = models.CharField(max_length=20, verbose_name='资源名称')
    down_load = models.FileField(upload_to='source/', verbose_name='下载路径', max_length=200)
    course_info = models.ForeignKey(CourseInfo, verbose_name='所属课程', on_delete=models.CASCADE)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '资源信息'
        verbose_name_plural = verbose_name

apps/orgs/models.py
from datetime import datetime

from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models


# Create your models here.
class CityInfo(models.Model):
    name = models.CharField(max_length=20, verbose_name='城市名称')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '城市信息'
        verbose_name_plural = verbose_name


class OrgInfo(models.Model):
    image = models.ImageField(upload_to='org/', max_length=200, verbose_name='机构封面')
    name = models.CharField(max_length=20, verbose_name='机构名称')

    course_num = models.IntegerField(default=0, verbose_name='课程数')
    study_num = models.IntegerField(default=0, verbose_name='学习人数')
    love_num = models.IntegerField(default=0, verbose_name='收藏数')
    click_num = models.IntegerField(default=0, verbose_name='访问量')

    address = models.CharField(max_length=200, verbose_name='机构地址')
    remark = models.CharField(max_length=200, verbose_name='机构简介')
    # detail = models.TextField(verbose_name='机构详情')
    detail = RichTextUploadingField(default='', verbose_name='机构详情')
    category = models.CharField(choices=(('pxjg', '培训机构'), ('gx', '高校'), ('gr', '个人')), max_length=10,
                                verbose_name='机构类别')
    # 关联关系
    city_info = models.ForeignKey(CityInfo, verbose_name='所在城市', on_delete=models.CASCADE)

    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '机构信息'
        verbose_name_plural = verbose_name


class TeacherInfo(models.Model):
    image = models.ImageField(upload_to='teacher/', max_length=200, verbose_name='讲师头像')
    name = models.CharField(max_length=20, verbose_name='讲师名字')
    work_year = models.IntegerField(default=3, verbose_name='工作年限')
    work_position = models.CharField(max_length=20, verbose_name='工作职位')
    work_style = models.CharField(max_length=20, verbose_name='教学特点')
    # 外键 机构
    work_company = models.ForeignKey(OrgInfo, verbose_name='所属机构', on_delete=models.CASCADE)
    age = models.IntegerField(default=30, verbose_name='教师年龄')

    love_num = models.IntegerField(default=0, verbose_name='收藏数')
    click_num = models.IntegerField(default=0, verbose_name='访问量')

    # 课程
    # 待补充

    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '教师信息'
        verbose_name_plural = verbose_name

templates/orgs/org-detail-base.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    {% block css1 %} {% endblock %}
{% endblock %}

{#{% block title %}#}
{#    机构首页#}
{#{% endblock %}#}

{% block middle %}

    <div class="middle companyheader">
        <div class="wp">
            <img class="fl" style="width: 112px;height: 103px" src="{{ MEDIA_URL }}{{ org.image }}"
                 alt="{{ org.name }}"/>
            <div class="head fl">
                <h1>
                    {#                    爱时尚教育网#}
                    {{ org.name }}
                    <img src="{% static 'images/authentication.png' %}" alt="认证"/>
                    <img src="{% static 'images/gold.png' %}" alt="金牌"/>
                </h1>
                <p class="fl">
                    <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                    <span class="precision company-credit" data-star-scope="5.0"></span>
                    <span class="key">5.0</span>
                </p>
            </div>
            <div class="btn fr collectionbtn  notlogin
                 " data-favid="22" data-fav-type="1" id="love">
                {% if love_status %} 取消收藏 {% else %} 收藏 {% endif %}
            </div>

        </div>
    </div>

{% endblock %}

{% block content %}

    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'orgs:org_list' %}">课程机构</a>></li>
                <li>{% block breach %}机构首页{% endblock %}</li>
            </ul>
        </div>
    </section>

    <section>
        <div class="wp list personal_list comp">
            <div class="left">
                <ul>

                    <li {% if request.resolver_match.url_name == 'org_detail' %}
                        class="active2" {% endif %}>

                        <a href="{% url 'orgs:org_detail' org.id %}">
                            机构首页
                        </a>
                    </li>

                    <li {% if request.resolver_match.url_name == 'org_detail_course' %} class="active2" {% endif %}>
                        <a href="{% url 'orgs:org_detail_course' org.id %}">
                            机构课程
                        </a>
                    </li>

                    <li {% if request.resolver_match.url_name == 'org_detail_desc' %} class="active2" {% endif %}>
                        <a href="{% url 'orgs:org_detail_desc' org.id %}">
                            机构介绍
                        </a>
                    </li>

                    <li {% if request.resolver_match.url_name == 'org_detail_teachers' %} class="active2" {% endif %} >
                        <a href="{% url 'orgs:org_detail_teachers' org.id %}">
                            机构讲师
                        </a>
                    </li>

                </ul>
            </div>

            {% block right %}{% endblock %}
        </div>

    </section>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'js/plugins/jquery.raty.js' %}"></script>

    <script type="text/javascript">
        $(function () {
            let $precision = $('.precision'),
                score = $precision.attr('data-star-scope'),
                option = {
                    half: true,
                    path: '{% static 'images' %}',
                    precision: true,
                    size: 24,
                    starOff: 'g_star.png',
                    starOn: 'r_star.png',
                    starHalf: 'h_star.png',
                    hints: ['极差', '差', '一般', '好评', '非常满意'],
                    noRatedMsg: '暂时还未获得评价！',
                    readOnly: true,
                    score: score
                };
            $precision.raty(option);
        })
    </script>

    <script>
        {#收藏分享#}
        $('#love').click(function () {
            {#let love_id = {{ org.id }};#}
            {#let love_type= 1;#}
            $.ajax({
                type: 'GET',
                url: '{% url "operations:user_love" %}',
                data: {
                    love_id:{{ org.id }},
                    {# 1 org 2 course 3 teacher #}
                    love_type: 1
                },
                success: function (callback) {
                    if (callback.status === 200) {
                        $('#love').text(callback.msg)
                    } else if (callback.status === 403) {
                        window.location.href = '{% url 'users:user_login' %}'
                    } else {
                        alert(callback.msg)
                    }
                }
            })
        })
    </script>

    {% block js1 %} {% endblock %}
{% endblock %}

templates/orgs/org-detail-desc.html
{% extends 'orgs/org-detail-base.html' %}

{% block title %}
    机构介绍
{% endblock %}

{% block breach %}
    机构介绍
{% endblock %}

{% block right %}
    <div class="right companycenter layout">
        <div class="head">
            <h1>机构介绍</h1>
        </div>
        <div class="des">

            <p>{{ org.detail|safe }}</p>

        </div>
    </div>
{% endblock %}

templates/orgs/org-detail-homepage.html
{% extends 'orgs/org-detail-base.html' %}

{% block title %}
    机构首页
{% endblock %}

{% block breach %}
    机构首页
{% endblock %}

{% block right %}
    <div class="right companycenter layout grouping">
        <div class="head">
            <h1>全部课程</h1>
            <a class="green fr more" href="{% url 'courses:course_list' %}">查看更多 > </a>
        </div>

        <div class="brief group_list">

            {% for course in org.courseinfo_set.all %}
                <div class="module1_5 box">
                    <a href="{% url 'courses:course_detail' course.id %}">
                        <img width="214" src="{{ MEDIA_URL }}{{ course.image }}" alt="{{ course.name }}"/>
                    </a>
                    <div class="des">
                        <a href="{% url 'courses:course_detail' course.id %}">
                            <h2>{{ course.name }}</h2>
                        </a>
                        <span class="fl">课时：
                            <i class="key">{{ course.study_time }}</i>
                        </span>
                        <span class="fr">参加人数：{{ course.study_num }}</span>
                    </div>
                    <div class="bottom">
                        <span class="fl">{{ org.name }}</span>
                        <span class="star fr  notlogin
                            " data-favid="13" data-fav-type="4">
                            {{ course.love_num }}
                        </span>
                    </div>
                </div>
            {% endfor %}

        </div>

    </div>

    <div class="right companycenter layout">
        <div class="head">
            <h1>机构教师</h1>
            <a class="green fr more" href="{% url 'orgs:org_detail_teachers' org.id %}">查看更多 > </a>
        </div>

        {% for teacher in org.teacherinfo_set.all %}
            <div class="diarys">
                <div class="module5 share company-diary-box" style="padding:10px 0;">
                    <div class="left">
                        <img class="pic" src="{{ MEDIA_URL }}{{ teacher.image }}" alt="{{ teacher.name }}"/>
                        <p>昵称：{{ teacher.name }}</p>
                    </div>
                    <div class="right">
                        <div class="top">
                            <div class="fl">
                                {#  问题：teacher.courseinfo_set.all.0.id 会咩有值 但不是空 #}
                                {% if teacher.courseinfo_set.all %}
                                    <a href="{% url 'courses:course_detail' teacher.courseinfo_set.all.0.id %}">
                                        <h1>{{ teacher.courseinfo_set.all.0 }}</h1>
                                    </a>
                                    <span>发表于：{{ teacher.courseinfo_set.all.0.add_time }}</span>
                                    </div>
                                {% endif %}
                        </div>
                        <div class="middle" style="border-bottom:0;">{{ teacher.courseinfo_set.all.0.desc }}</div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="right companycenter layout">
        <div class="head">
            <h1>机构介绍</h1>
            <a class="green fr more" href="{% url 'orgs:org_detail_desc' org.id %}">查看更多 > </a>
        </div>
        <div class="cont">
            <p>{{ org.remark }}</p>
        </div>
    </div>

{% endblock %}

templates/orgs/org-detail-teachers.html
{% extends 'orgs/org-detail-base.html' %}

{% block title %}
    机构教师
{% endblock %}

{% block breach %}
    机构教师
{% endblock %}

{% block right %}
    <div class="right companycenter layout">
        <div class="head">
            <h1>机构讲师</h1>
        </div>
        <div class="messagelist">
            <div class=" butler_list butler-fav-box">

                {% for teacher in org.teacherinfo_set.all %}
                    <dl class="des users">
                        <dt>
                            <a href="{% url 'orgs:teacher_detail' teacher.id %}">
                                <img width="100" height="100" class="scrollLoading"
                                     data-url="{{ MEDIA_URL }}{{ teacher.image }}"
                                     src="{{ MEDIA_URL }}{{ teacher.image }}" alt="{{ teacher.name }}"/>
                            </a>
                        </dt>
                        <dd>
                            <h1>
                                <a href="{% url 'orgs:teacher_detail' teacher.id %}">
                                    {{ teacher.name }}
                                    <span class="key">已认证</span>
                                </a>
                            </h1>
                            <ul class="cont clearfix">
                                <li class="time">工作年限：
                                    <span>{{ teacher.work_year }}年</span>
                                </li>
                                <li class="c7" style="padding-left:inherit">
                                    课程数：<span>{{ teacher.courseinfo_set.all.count }}</span>
                                </li>
                            </ul>
                        </dd>
                    </dl>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/orgs/teacher-detail.html
{% extends 'base.html' %}

{% block title %}
    讲师详情
{% endblock %}

{% block content %}

    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="/">首页</a>></li>
                <li><a href="{% url 'orgs:teacher_list' %}">授课讲师</a>></li>
                <li>讲师详情</li>
            </ul>
        </div>
    </section>

    <section>
        <div class="wp butler-detail-box butler-diaryd-box clearfix">
            <div class="fl list">
                <div class="butler_detail_list clearfix">
                    <div class="brief">
                        <dl class="des">
                            <dt>
                                <div class="picpic">
                                    <img width="100" height="100" src="{{ MEDIA_URL }}{{ teacher.image }}"
                                         alt="{{ teacher.name }}"/>
                                </div>
                                <div class="btn">
                                <span class="fl btn1 collectionbtn" id="jsLeftBtn">
                                     {% if love_teacher_status %} 取消收藏 {% else %} 收藏 {% endif %}
                                </span>
                                    <span class="fr btn2 shareBtn bdsharebuttonbox">
                                    <span class="fl">分享</span>
                                    <a href="#" class="bds_more" data-cmd="more"></a>
                                </span>
                                </div>
                            </dt>
                            <dd>
                                <a href="{% url 'orgs:teacher_detail' teacher.id %}">
                                    <h1>{{ teacher.name }}<span class="key picbig">金牌讲师</span></h1>
                                </a>
                                <ul class="cont">
                                    <li>工作年限：<span>{{ teacher.work_year }}</span></li>
                                    <li>就职公司：<span>{{ teacher.work_company.name }}&nbsp;</span></li>
                                    <li>工作职位：<span>{{ teacher.work_position }}</span></li>
                                    <li>教学特点：<span>{{ teacher.work_style }}</span></li>
                                </ul>
                            </dd>
                        </dl>
                    </div>
                </div>

                <div class="butler_detail_cont clearfix">
                    <div class="left layout">
                        <div class="head">
                            <ul class="tab_header">
                                <li class="active"><a href="{% url 'courses:course_list' %}">全部课程</a></li>
                            </ul>
                        </div>

                        <div class="companycenter">
                            <div class="group_list brief">
                                {% for course in teacher.courseinfo_set.all %}
                                    <div class="module1_5 box">
                                        <a href="{% url 'courses:course_detail' course.id %}">
                                            <img width="214" height="190" class="scrollLoading"
                                                 src="{{ MEDIA_URL }}{{ course.image }}" alt="{{ course.name }}"/>
                                        </a>
                                        <div class="des">
                                            <a href="{% url 'courses:course_detail' course.id %}">
                                                <h2>{{ course.name }}</h2></a>
                                            <span class="fl">时长：<i class="key">{{ course.study_time }}</i></span>
                                            <span class="fr">学习人数：{{ course.study_num }}</span>
                                        </div>
                                        <div class="bottom">
                                            <span class="fl">{{ course.org_info.name }}</span>
                                            <span class="star fr  notlogin" data-favid="15">{{ course.love_num }}</span>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>

                    </div>
                </div>
            </div>

            <div class="fr list">
                <div class="butler_detail_list">
                    <div class="right butler-company-box">
                        <div class="head">
                            <h1>{{ teacher.work_company.name }}</h1>
                            <p>{{ teacher.work_company.detail }}</p>
                        </div>
                        <div class="pic">
                            <a href="{% url 'orgs:org_detail' teacher.work_company.id %}">
                                <img width="150" height="80" src="{{ MEDIA_URL }}{{ teacher.work_company.image }}"
                                     alt="{{ teacher.work_company.name }}"/>
                            </a>
                        </div>
                        <a href="{% url 'orgs:org_detail' teacher.work_company.id %}">
                            <h2 class="center">{{ teacher.work_company.name }}</h2>
                        </a>
                        <p class="center tell">地址：{{ teacher.work_company.address }}</p>
                        <a class="btn" id="jsRightBtn">{% if love_status %} 取消收藏 {% else %} 收藏 {% endif %}</a>
                    </div>
                </div>

                <div class="butler_detail_cont">
                    <div class="butler_list_box">
                        <div class="right layout">
                            <div class="head">讲师排行榜</div>

                            {% for tea in sort_teachers %}
                                <dl class="des">
                                    <span class="num fl">{{ forloop.counter }}</span>
                                    <a href="{% url 'orgs:teacher_detail' tea.id %}">
                                        <dt>
                                            <img width="50" height="50" class="scrollLoading"
                                                 src="{{ MEDIA_URL }}{{ tea.image }}" alt="{{ tea.name }}"/>
                                        </dt>
                                    </a>
                                    <dd>
                                        <a href="{% url 'orgs:teacher_detail' tea.id %}">
                                            <h1 title="{{ tea.name }}">{{ tea.name }}</h1>
                                        </a>
                                        <p>工作年限：<span>{{ tea.work_year }}</span></p>
                                    </dd>
                                </dl>
                            {% endfor %}

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </section>

{% endblock %}

{% block js %}

    <script>
        $('#jsLeftBtn').click(function () {
            $.ajax({
                type: 'GET',
                url: '{% url "operations:user_love" %}',
                data: {
                    love_id:{{ teacher.id }},
                    {# 1 org 2 course 3 teacher #}
                    love_type: 3
                },
                success: function (callback) {
                    if (callback.status === 200) {
                        $('#jsLeftBtn').text(callback.msg)
                    } else {
                        alert(callback.msg)
                    }
                }
            })
        })
    </script>

    <script>
        $('#jsRightBtn').click(function () {
            $.ajax({
                type: 'GET',
                url: '{% url "operations:user_love" %}',
                data: {
                    love_id:{{ teacher.work_company.id }},
                    {# 1 org 2 course 3 teacher #}
                    love_type: 1
                },
                success: function (callback) {
                    if (callback.status === 200) {
                        $('#jsRightBtn').text(callback.msg)
                    } else if (callback.status === 403) {
                        window.location.href = '{% url 'users:user_login' %}'
                    } else {
                        alert(callback.msg)
                    }
                }
            })
        })

    </script>
{% endblock %}