Django_/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Django_ import settings
from users.views import IndexView

urlpatterns = [
                  # 首页直接进行跳转
                  path('', IndexView.as_view(), name='index'),
                  path('admin/', admin.site.urls),
                  path('captcha/', include('captcha.urls')),
                  path('ckeditor/', include('ckeditor_uploader.urls')),
                  # version more better I have last version
                  # path('ueditor/', include('DjangoUeditor.urls')),
                  # path('xadmin/', xadmin.site.urls),
                  path('users/', include(('users.urls', 'users'), namespace='users')),
                  path('courses/', include(('courses.urls', 'courses'), namespace='courses')),
                  path('orgs/', include(('orgs.urls', 'orgs'), namespace='orgs')),
                  path('operations/', include(('operations.urls', 'operations'), namespace='operations')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'users.views.handle_404'
handler500 = 'users.views.handler_500'

apps/courses/urls.py
from django.urls import path, re_path

from .views import CourseListView, CourseDetailView, CourseVideoView, CourseCommentView

urlpatterns = [
    path('course_list/', CourseListView.as_view(), name='course_list'),
    re_path('course_detail/(\\d+)', CourseDetailView.as_view(), name='course_detail'),
    re_path('course_video/(\\d+)', CourseVideoView.as_view(), name='course_video'),
    re_path('course_comment/(\\d+)', CourseCommentView.as_view(), name='course_comment'),
]

apps/operations/urls.py
from django.urls import path

from .views import UserAskView, UserLoveView, UserDeleteLoveView, UserCommentView, UserMessageView

urlpatterns = [
    path('user_ask/', UserAskView.as_view(), name='user_ask'),

    path('user_love/', UserLoveView.as_view(), name='user_love'),
    path('user_delete_love/', UserDeleteLoveView.as_view(), name='user_delete_love'),

    path('user_comment/', UserCommentView.as_view(), name='user_comment'),
    path('user_message/', UserMessageView.as_view(), name='user_message'),
]

apps/orgs/urls.py
from django.urls import path, re_path

from .views import OrgListView, OrgDetailView, OrgDetailCourseView, OrgDetailDescView, OrgDetailTeachersView, \
    TeacherListView, TeacherDetailView

urlpatterns = [
    path('org_list/', OrgListView.as_view(), name='org_list'),
    re_path('org_detail/(\\d+)', OrgDetailView.as_view(), name='org_detail'),
    re_path('org_detail_course/(\\d+)', OrgDetailCourseView.as_view(), name='org_detail_course'),
    re_path('org_detail_desc/(\\d+)', OrgDetailDescView.as_view(), name='org_detail_desc'),
    re_path('org_detail_teachers/(\\d+)', OrgDetailTeachersView.as_view(), name='org_detail_teachers'),
    # teacher
    path('teacher_list/', TeacherListView.as_view(), name='teacher_list'),
    re_path('teacher_detail/(\\d+)', TeacherDetailView.as_view(), name='teacher_detail'),
]

apps/users/urls.py
from django.urls import path, re_path

from .views import UserRegisterView, UserLoginView, UserLogoutView, UserActiveView, UserForgetView, UserResetView, \
    UserInfoView, UserChangeImageView, UserChangeInfoView, UserChangeEmailView, UserRestEmailView, UserCourseView, \
    UserLoveOrgView, UserLoveCourseView, UserLoveTeacherView, UserMessageView

urlpatterns = [
    # name 必须是 'xxx'
    path('user_register/', UserRegisterView.as_view(), name='user_register'),
    path('user_login/', UserLoginView.as_view(), name='user_login'),
    path('user_logout/', UserLogoutView.as_view(), name='user_logout'),
    # 如果要使用正则表达式 需要使用re_path
    re_path('user_active/(\\w+)/', UserActiveView.as_view(), name='user_active'),

    path('user_forget/', UserForgetView.as_view(), name='user_forget'),
    re_path('user_reset/(\\w+)/', UserResetView.as_view(), name='user_reset'),

    path('user_info/', UserInfoView.as_view(), name='user_info'),
    path('user_change_image/', UserChangeImageView.as_view(), name='user_change_image'),
    path('user_change_info/', UserChangeInfoView.as_view(), name='user_change_info'),
    path('user_change_email/', UserChangeEmailView.as_view(), name='user_change_email'),
    path('user_rest_email/', UserRestEmailView.as_view(), name='user_rest_email'),

    path('user_course/', UserCourseView.as_view(), name='user_course'),
    path('user_love_org/', UserLoveOrgView.as_view(), name='user_love_org'),
    path('user_love_teacher/', UserLoveTeacherView.as_view(), name='user_love_teacher'),
    path('user_love_course/', UserLoveCourseView.as_view(), name='user_love_course'),

    path('user_message/', UserMessageView.as_view(), name='user_message'),
]

templates/base.html
<!DOCTYPE html>

{# 加载静态文件 #}
{% load static %}

<html>

<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    {% block css %} {% endblock %}

    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>

</head>
<body>
<section class="headerwrap">
    <header>
        <div class="header2 header">

            <div class="top">
                <div class="wp">
                    <div class="fl"><p>服务电话：<b>8888888</b></p></div>

                    <!--登录后跳转-->
                    <!-- 判断是否登陆 后台admin登陆 默认登陆 -->
                    {% if request.user.is_authenticated %}
                        <div class="personal">
                            <dl class="user fr">
                                <dd>{{ request.user.username }}
                                    <img class="down fr" src="{% static 'images/top_down.png' %}"/>
                                </dd>
                                <dt>
                                    <img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/>
                                </dt>
                            </dl>
                            <div class="userdetail">
                                <dl>
                                    <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                                    <dd>
                                        <h2>django</h2>
                                        <p>{{ request.user.username }}</p>
                                    </dd>
                                </dl>
                                <div class="btn">
                                    <a class="personcenter fl" href="{% url 'users:user_info' %}">进入个人中心</a>
                                    <a class="fr" href="{% url 'users:user_logout' %}">退出</a>
                                </div>
                            </div>

                            {#   消息通知  #}
                            {# {% if request.path.startswith('/users') %}#}
                            <a href="{% url 'users:user_message' %}">
                                <div class="msg-num">
                                    <span id="MsgNum">{{ request.user.get_message_count }}</span>
                                </div>
                            </a>
                            {#{% endif %}#}
                        </div>
                    {% else %}
                        <a style="color:white" class="fr registerbtn" href="{% url 'users:user_register' %}">注册</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'users:user_login' %}">登录</a>
                    {% endif %}

                </div>
            </div>

            {% block middle %}
                <div class="middle">
                    <div class="wp">
                        <a href="{% url 'index' %}"><img class="fl" src="{% static 'images/logo1.png' %}"/></a>
                        <div class="searchbox fr">
                            <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                公开课
                            </span>
                                <ul class="selectMenu" id="jsSelectMenu">
                                    <li data-value="course">公开课</li>
                                    <li data-value="org">课程机构</li>
                                    <li data-value="teacher">授课老师</li>
                                </ul>
                            </div>
                            <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
                            <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %}"/>
                        </div>
                    </div>
                </div>

                <nav>
                    <div class="nav">
                        <div class="wp">
                            <ul>
                                <li {% if request.path == '/' %} class="active" {% endif %}>
                                    <a href="{% url 'index' %}">
                                        首页
                                    </a>
                                </li>
                                <li {% if 'courses' in request.path %} class="active" {% endif %}>
                                    <a href="{% url 'courses:course_list' %}">
                                        公开课<img class="hot" src="{% static 'images/nav_hot.png' %}" alt="hot">
                                    </a>
                                </li>
                                <li
                                        {% if request.path == '/orgs/teacher_list/' or request.resolver_match.url_name == 'teacher_detail' %}
                                            class="active" {% endif %}>
                                    <a href="{% url 'orgs:teacher_list' %}">
                                        授课教师
                                    </a>
                                </li>
                                <li {% if request.path == '/orgs/org_list/' %} class="active" {% endif %}>
                                    <a href="{% url 'orgs:org_list' %}">
                                        授课机构
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
            {% endblock %}

        </div>
    </header>
</section>
<!--crumbs start-->

{% block content %} {% endblock %}

{% block footer %}
    <footer>
        <div class="footer">
            <div class="wp">
                <ul class="cont">
                    <li class="logo">
                        <a href="">
                            <img src="{% static 'images/logo1.png' %}"/>
                        </a>
                    </li>
                    <li class="code">
                        <img src="{% static 'images/weixi_icon2.png' %}"/>
                        <p class="center">扫描关注微信</p>
                    </li>
                    <li class="third">
                        <img class="fl" src="{% static 'images/tell.png' %}"/>
                        <p class="tell">88888888</p>
                        <p class="time">周一至周日 9:00-18:00</p>
                    </li>
                </ul>

            </div>
            <p class="line"></p>
            <div class="wp clear">
                <span class="fl">? 2012 www.atguigu.com爱时尚教育-在线学习交流平台 保留所有权利</span>
                <span class="fr">copyright ? 2012 ICP备案证书号：蜀ICP备xxxxx号-1</span>
            </div>
        </div>
    </footer>
{% endblock %}

<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>

<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}" type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}" type="text/javascript"></script>

<script type="text/javascript" src="{% static 'js/index.js' %}"></script>

<script>

    {# overall situation search  #}
    $(function () {
        $('#jsSearchBtn').click(function () {
            let operation_type = $('#jsSelectOption').attr('data-value')
            let search_name = $('#search_keywords').val()
            let url = ''

            switch (operation_type) {
                case 'org':
                    url = '{% url 'orgs:org_list' %}'
                    break;
                case "course":
                    url = '{% url 'courses:course_list' %}'
                    break;
                case "teacher":
                    url = '{% url 'orgs:teacher_list' %}'
                    break;
            }

            url = url + '?keyword=' + search_name
            window.location.href = url

            {#$.ajax({#}
            {#    type: "GET",#}
            {#    url: url,#}
            {#    data: {#}
            {#        type: operation_type,#}
            {#        name: search_name#}
            {#    },#}
            {#    success: function (callback) {#}
            {#        if(callback.status === 200){#}
            {#            alert(callback.msg)#}
            {#        }else {#}
            {#            alert(callback.msg)#}
            {#        }#}
            {#    }#}
            {# }) #}
        })
    })

</script>

{% block js %} {% endblock %}
</body>
</html>

templates/forgetpwd.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>爱时尚教育首页</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
</head>
<body>
<!--提示弹出框-->
{# 没有对应的js #}
{#<div class="successbox dialogbox" id="jsSuccessTips">#}
{#    <h1>成功提交</h1>#}
{#    <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>#}
{#    <div class="cont">#}
{#        <h2>您的需求提交成功！</h2>#}
{#        <p></p>#}
{#    </div>#}
{#</div>#}
{#<div class="resetpassbox dialogbox" id="jsSetNewPwd">#}
{#    <h1>重新设置密码</h1>#}
{#    <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>#}
{#    <p class="green">请输入新密码</p>#}
{#    <form id="jsSetNewPwdForm">#}
{#        <div class="box">#}
{#            <span class="word2">密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</span>#}
{#            <input type="password" name="password" id="jsResetPwd" placeholder="请输入新密码"/>#}
{#        </div>#}
{#        <div class="box">#}
{#            <span class="word2">确&nbsp;认&nbsp;密&nbsp;码</span>#}
{#            <input type="password" name="password2" id="jsResetPwd2" placeholder="请再次输入新密码"/>#}
{#        </div>#}
{#        <div class="box">#}
{#            <span class="word2">验&nbsp;&nbsp;证&nbsp;&nbsp;码</span>#}
{#            <input type="text" name="code" id="jsResetCode" placeholder="请输入手机验证码"/>#}
{#        </div>#}
{#        <div class="error btns" id="jsSetNewPwdTips"></div>#}
{#        <div class="button">#}
{#            <input type="hidden" name="mobile" id="jsInpResetMobil" />#}
{#            <input id="jsSetNewPwdBtn" type="button" value="提交" />#}
{#        </div>#}
{#    </form>#}
{#</div>#}
{#<div class="bg" id="dialogBg"></div>#}
<header>
    <div class="c-box fff-box">
        <div class="wp header-box">
            <p class="fl hd-tips">爱时尚教育，在线学习平台！</p>
            <ul class="fr hd-bar">
                <li>服务电话：<span>88888888</span></li>
                <li><a href="login.html">[登录]</a></li>
                <li class="active"><a href="/forgetpwd/">[忘记密码]</a></li>
            </ul>
        </div>
    </div>
</header>
<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href="{% url 'index' %}"></a>
                <h1>忘记密码</h1>
                <a class="index-font" href="{% url 'index' %}">回到首页</a>
            </div>
            <div class="fl slide">
                <div class="imgslide">
                    <ul class="imgs">
                        <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}" /></a></li>
                        <li><a href=""><img width="483" height="472" src="{% static 'images/mongoDB.jpg' %}" /></a></li>
                        <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}" /></a></li>
                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
            <div class="fl form-box">
                <h2>忘记密码</h2>
                <form id="jsFindPwdForm" method="post" action="{% url 'users:user_forget' %}" autocomplete="off">
                    {% csrf_token %}
                    <div class="form-group marb20 ">
                        <label>帐&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;号</label>
                        <input type="text" id="account" name="email" value="" placeholder="邮箱" />
                    </div>
                    <div class="form-group captcha1 marb38">
                        <label>验&nbsp;证&nbsp;码</label>
                        {{ user_forget_form.captcha }}
                    </div>
                    <div class="error btns" id="jsForgetTips">
                        {{ msg }}
                        {% for key,err in user_forget_form.errors.items %}
                            {{ err }}
                        {% endfor %}
                    </div>
                    <input type="hidden" name="sms_type" value="1">
                    <input class="btn btn-green" id="jsFindPwdBtn" type="submit" value="提交" />
                    <p class="form-p" style="bottom:40px;">您还可以<a href="{% url 'users:user_login' %}"> [直接登录]</a></p>
                </form>
            </div>
        </div>
    </div>
</section>

<input id="isLogin" type="hidden" value="False"/>
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/validateDialog.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/login.js' %}"  type="text/javascript"></script>
</body>
</html>

templates/handle_404.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>404</title>
    <style>
        p {
            color: red;
        }
    </style>
</head>
<body>
<p>404！你访问的页面不存在</p>
</body>
</html>

templates/handler_500.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>500</title>
<style>
    p{
        color: white;
        background-color: pink;
    }
</style>
</head>
<body>
<p>500!您请求的参数有误，请检查后重新尝试</p>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    首页-爱时尚教育
{% endblock %}

{% block content %}

    <div class="banner">
        <div class="wp">
            <div class="fl">
                <div class="imgslide">
                    <ul class="imgs">
                        {% for banner in banners %}
                            <li>
                                <a href="{{ banner.url }}">
                                    <img width="1200" height="478" src="{{ MEDIA_URL }}{{ banner.image }}"
                                         alt="{{ banner.id }}"/>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>

        </div>

    </div>

    <section>
        <div class="wp">
            <ul class="feature">
                <li class="feature1">
                    <img class="pic" src="{% static 'images/feature5.png' %}" alt="23:04"/>
                    <p class="center">专业权威</p>
                </li>
                <li class="feature2">
                    <img class="pic" src="{% static 'images/feature5.png' %}" alt="23:04"/>
                    <p class="center">课程最新</p>
                </li>
                <li class="feature3">
                    <img class="pic" src="{% static 'images/feature5.png' %}" alt="23:04"/>
                    <p class="center">名师授课</p>
                </li>
                <li class="feature4">
                    <img class="pic" src="{% static 'images/feature5.png' %}" alt="23:04"/>
                    <p class="center">数据真实</p>
                </li>
            </ul>
        </div>
    </section>

    <section>
        <div class="module">
            <div class="wp">
                <h1>公开课程</h1>
                <div class="module1 eachmod">
                    <div class="module1_1 left">
                        <img width="228" height="614" src="{% static 'images/module5_1.jpg' %}"/>
                        <p class="fisrt_word">名师授课<br/>专业权威</p>
                        <a class="more" href="{% url 'courses:course_list' %}">查看更多课程 ></a>
                    </div>
                    <div class="right group_list">
                        <div class="module1_2 box">
                            <div class="imgslide2">
                                <ul class="imgs">

                                    {% for banner_cours in banner_courses %}
                                        <li>
                                            <a href="{% url 'courses:course_detail' banner_cours.id %}">
                                                <img width="470" height="300"
                                                     src="{{ MEDIA_URL }}{{ banner_cours.image }}"
                                                     alt="{{ banner_cours.name }}"/>
                                            </a>
                                        </li>
                                    {% endfor %}

                                </ul>
                            </div>
                            <div class="unslider-arrow2 prev"></div>
                            <div class="unslider-arrow2 next"></div>
                        </div>

                        {% for course in courses %}
                            <div class="module1_{{ forloop.counter|add:"2" }} box">
                                <a href="{% url 'courses:course_detail' course.id %}">
                                    <img width="233" height="190" src="{{ MEDIA_URL }}{{ course.image }}"
                                         alt="{{ course.name }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'courses:course_detail' course.id %}">
                                        <h2 title="{{ course.name }}">{{ course.name }}</h2>
                                    </a>

                                    <span class="fl">难度：
                                        <i class="key">
                                            {% if course.level == 'cj' %} 初级
                                            {% elif course.level == 'zj' %} 中级
                                            {% else %} 高级
                                            {% endif %}
                                        </i>
                                    </span>

                                    <span class="fr">学习人数：{{ course.study_num }}</span>
                                </div>
                                <div class="bottom">
                                    <span class="fl"
                                          title="{{ course.org_info.name }}">{{ course.org_info.name }}</span>
                                    <span class="star fr">{{ course.love_num }}</span>
                                </div>
                            </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </section>

    <section>
        <div class="module greybg">
            <div class="wp">
                <h1>课程机构</h1>
                <div class="module3 eachmod">
                    <div class="module3_1 left">
                        <img width="228" height="463" src="{% static 'images/module6_1.jpg' %}"/>
                        <p class="fisrt_word">名校来袭<br/>权威认证</p>
                        <a class="more" href="{% url 'orgs:org_list' %}">查看更多机构 ></a>
                    </div>
                    <div class="right">
                        <ul>
                            {% for org in orgs %}
                                <li class="">
                                    <a href="{% url 'orgs:org_detail' org.id %}">
                                        <div class="company">
                                            <img width="184" height="100" src="{{ MEDIA_URL }}{{ org.image }}"
                                                 alt="{{ org.name }}"/>
                                            <div class="score">
                                                <div class="circle">
                                                    <h2>全国知名</h2>
                                                </div>
                                            </div>
                                        </div>
                                        <p><span class="key" title="{{ org.name }}">{{ org.name }}</span></p>
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}