Django_/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Django_ import settings
from users.views import IndexView

urlpatterns = [
                  # 首页直接进行跳转
                  path('', IndexView.as_view(), name='index'),
                  path('admin/', admin.site.urls),
                  path('captcha/', include('captcha.urls')),
                  path('ckeditor/', include('ckeditor_uploader.urls')),
                  # version more better I have last version
                  # path('ueditor/', include('DjangoUeditor.urls')),
                  # path('xadmin/', xadmin.site.urls),
                  path('users/', include(('users.urls', 'users'), namespace='users')),
                  path('courses/', include(('courses.urls', 'courses'), namespace='courses')),
                  path('orgs/', include(('orgs.urls', 'orgs'), namespace='orgs')),
                  path('operations/', include(('operations.urls', 'operations'), namespace='operations')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'users.views.handle_404'
handler500 = 'users.views.handler_500'

apps/courses/urls.py
from django.urls import path, re_path

from .views import CourseListView, CourseDetailView, CourseVideoView, CourseCommentView

urlpatterns = [
    path('course_list/', CourseListView.as_view(), name='course_list'),
    re_path('course_detail/(\\d+)', CourseDetailView.as_view(), name='course_detail'),
    re_path('course_video/(\\d+)', CourseVideoView.as_view(), name='course_video'),
    re_path('course_comment/(\\d+)', CourseCommentView.as_view(), name='course_comment'),
]

apps/operations/urls.py
from django.urls import path

from .views import UserAskView, UserLoveView, UserDeleteLoveView, UserCommentView, UserMessageView

urlpatterns = [
    path('user_ask/', UserAskView.as_view(), name='user_ask'),

    path('user_love/', UserLoveView.as_view(), name='user_love'),
    path('user_delete_love/', UserDeleteLoveView.as_view(), name='user_delete_love'),

    path('user_comment/', UserCommentView.as_view(), name='user_comment'),
    path('user_message/', UserMessageView.as_view(), name='user_message'),
]

apps/orgs/urls.py
from django.urls import path, re_path

from .views import OrgListView, OrgDetailView, OrgDetailCourseView, OrgDetailDescView, OrgDetailTeachersView, \
    TeacherListView, TeacherDetailView

urlpatterns = [
    path('org_list/', OrgListView.as_view(), name='org_list'),
    re_path('org_detail/(\\d+)', OrgDetailView.as_view(), name='org_detail'),
    re_path('org_detail_course/(\\d+)', OrgDetailCourseView.as_view(), name='org_detail_course'),
    re_path('org_detail_desc/(\\d+)', OrgDetailDescView.as_view(), name='org_detail_desc'),
    re_path('org_detail_teachers/(\\d+)', OrgDetailTeachersView.as_view(), name='org_detail_teachers'),
    # teacher
    path('teacher_list/', TeacherListView.as_view(), name='teacher_list'),
    re_path('teacher_detail/(\\d+)', TeacherDetailView.as_view(), name='teacher_detail'),
]

apps/users/urls.py
from django.urls import path, re_path

from .views import UserRegisterView, UserLoginView, UserLogoutView, UserActiveView, UserForgetView, UserResetView, \
    UserInfoView, UserChangeImageView, UserChangeInfoView, UserChangeEmailView, UserRestEmailView, UserCourseView, \
    UserLoveOrgView, UserLoveCourseView, UserLoveTeacherView, UserMessageView

urlpatterns = [
    # name 必须是 'xxx'
    path('user_register/', UserRegisterView.as_view(), name='user_register'),
    path('user_login/', UserLoginView.as_view(), name='user_login'),
    path('user_logout/', UserLogoutView.as_view(), name='user_logout'),
    # 如果要使用正则表达式 需要使用re_path
    re_path('user_active/(\\w+)/', UserActiveView.as_view(), name='user_active'),

    path('user_forget/', UserForgetView.as_view(), name='user_forget'),
    re_path('user_reset/(\\w+)/', UserResetView.as_view(), name='user_reset'),

    path('user_info/', UserInfoView.as_view(), name='user_info'),
    path('user_change_image/', UserChangeImageView.as_view(), name='user_change_image'),
    path('user_change_info/', UserChangeInfoView.as_view(), name='user_change_info'),
    path('user_change_email/', UserChangeEmailView.as_view(), name='user_change_email'),
    path('user_rest_email/', UserRestEmailView.as_view(), name='user_rest_email'),

    path('user_course/', UserCourseView.as_view(), name='user_course'),
    path('user_love_org/', UserLoveOrgView.as_view(), name='user_love_org'),
    path('user_love_teacher/', UserLoveTeacherView.as_view(), name='user_love_teacher'),
    path('user_love_course/', UserLoveCourseView.as_view(), name='user_love_course'),

    path('user_message/', UserMessageView.as_view(), name='user_message'),
]

apps/courses/models.py
from datetime import datetime

from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models

from orgs.models import OrgInfo, TeacherInfo


# Create your models here.
class CourseInfo(models.Model):
    image = models.ImageField(upload_to='course/', verbose_name='课程封面', max_length=200)
    name = models.CharField(max_length=20, verbose_name='课程名称')
    is_banner = models.BooleanField(default=False, verbose_name='是否轮播')

    study_time = models.IntegerField(default=0, verbose_name='学习时长')
    study_num = models.IntegerField(default=0, verbose_name='学习人数')
    level = models.CharField(choices=(('gj', '高级'), ('zj', '中级'), ('cj', '初级')), default='cj', max_length=3,
                             verbose_name='难度')

    love_num = models.IntegerField(default=0, verbose_name='收藏数')
    click_num = models.IntegerField(default=0, verbose_name='访问量')

    desc = models.CharField(verbose_name='课程简介', max_length=200)
    # detail = models.TextField(verbose_name='课程详情')
    detail = RichTextUploadingField(default='', verbose_name='课程详情')

    category = models.CharField(choices=(('qd', '前端开发'), ('hd', '后端开发')), default='hd',
                                verbose_name='课程类别', max_length=20)

    course_notice = models.CharField(max_length=200, verbose_name='课程公告')
    course_need = models.CharField(max_length=200, verbose_name='课程须知')
    teacher_tell = models.CharField(max_length=200, verbose_name='老师告诉')
    org_info = models.ForeignKey(OrgInfo, verbose_name='所属机构', on_delete=models.CASCADE)
    teacher_info = models.ForeignKey(TeacherInfo, verbose_name='所属讲师', on_delete=models.CASCADE)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '课程信息'
        verbose_name_plural = verbose_name


# 章节信息
class ChapterInfo(models.Model):
    name = models.CharField(max_length=20, verbose_name='章节名称')
    course_info = models.ForeignKey(CourseInfo, verbose_name='所属课程', on_delete=models.CASCADE)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '章节信息'
        verbose_name_plural = verbose_name


class VideoInfo(models.Model):
    name = models.CharField(max_length=20, verbose_name='视频名称')
    study_time = models.IntegerField(default=0, verbose_name='视频时长')
    url = models.URLField(default='https://www.baidu.com', verbose_name='视频链接', max_length=200)
    chapter_info = models.ForeignKey(ChapterInfo, verbose_name='所属章节', on_delete=models.CASCADE)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '视频信息'
        verbose_name_plural = verbose_name


class SourceInfo(models.Model):
    name = models.CharField(max_length=20, verbose_name='资源名称')
    down_load = models.FileField(upload_to='source/', verbose_name='下载路径', max_length=200)
    course_info = models.ForeignKey(CourseInfo, verbose_name='所属课程', on_delete=models.CASCADE)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '资源信息'
        verbose_name_plural = verbose_name

apps/orgs/models.py
from datetime import datetime

from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models


# Create your models here.
class CityInfo(models.Model):
    name = models.CharField(max_length=20, verbose_name='城市名称')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '城市信息'
        verbose_name_plural = verbose_name


class OrgInfo(models.Model):
    image = models.ImageField(upload_to='org/', max_length=200, verbose_name='机构封面')
    name = models.CharField(max_length=20, verbose_name='机构名称')

    course_num = models.IntegerField(default=0, verbose_name='课程数')
    study_num = models.IntegerField(default=0, verbose_name='学习人数')
    love_num = models.IntegerField(default=0, verbose_name='收藏数')
    click_num = models.IntegerField(default=0, verbose_name='访问量')

    address = models.CharField(max_length=200, verbose_name='机构地址')
    remark = models.CharField(max_length=200, verbose_name='机构简介')
    # detail = models.TextField(verbose_name='机构详情')
    detail = RichTextUploadingField(default='', verbose_name='机构详情')
    category = models.CharField(choices=(('pxjg', '培训机构'), ('gx', '高校'), ('gr', '个人')), max_length=10,
                                verbose_name='机构类别')
    # 关联关系
    city_info = models.ForeignKey(CityInfo, verbose_name='所在城市', on_delete=models.CASCADE)

    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '机构信息'
        verbose_name_plural = verbose_name


class TeacherInfo(models.Model):
    image = models.ImageField(upload_to='teacher/', max_length=200, verbose_name='讲师头像')
    name = models.CharField(max_length=20, verbose_name='讲师名字')
    work_year = models.IntegerField(default=3, verbose_name='工作年限')
    work_position = models.CharField(max_length=20, verbose_name='工作职位')
    work_style = models.CharField(max_length=20, verbose_name='教学特点')
    # 外键 机构
    work_company = models.ForeignKey(OrgInfo, verbose_name='所属机构', on_delete=models.CASCADE)
    age = models.IntegerField(default=30, verbose_name='教师年龄')

    love_num = models.IntegerField(default=0, verbose_name='收藏数')
    click_num = models.IntegerField(default=0, verbose_name='访问量')

    # 课程
    # 待补充

    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '教师信息'
        verbose_name_plural = verbose_name

apps/courses/views.py
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import View

from operations.models import UserCommentInfo
from operations.models import UserCourseInfo
from utils.common_tool import get_love_status
# from django.contrib.auth.decorators import login_required
from utils.decorators import login_decorators
from utils.page_tool import page
from .models import CourseInfo


# Create your views here.
class CourseListView(View):
    def get(self, request):
        all_courses = CourseInfo.objects.all()
        recommend_courses = all_courses.order_by('-add_time')[:3]

        sort = request.GET.get('sort', '')
        if sort:
            print(fr'-{sort}')
            all_courses = all_courses.order_by(fr'-{sort}')

        keyword = request.GET.get('keyword', '')
        if keyword:
            all_courses = all_courses.filter(
                Q(name__icontains=keyword) | Q(desc__icontains=keyword) | Q(detail__icontains=keyword))
        # 分页
        pages = page(request, all_courses)

        return render(request, 'courses/course-list.html', {
            'all_courses': all_courses,
            'recommend_courses': recommend_courses,
            'pages': pages,
            'sort': sort,
            'keyword': keyword
        })


# def course_list(request):
#     all_courses = CourseInfo.objects.all()
#     recommend_courses = all_courses.order_by('-add_time')[:3]
#
#     sort = request.GET.get('sort', '')
#     if sort:
#         print(fr'-{sort}')
#         all_courses = all_courses.order_by(fr'-{sort}')
#
#     keyword = request.GET.get('keyword', '')
#     if keyword:
#         all_courses = all_courses.filter(
#             Q(name__icontains=keyword) | Q(desc__icontains=keyword) | Q(detail__icontains=keyword))
#     # 分页
#     pages = page(request, all_courses)
#
#     return render(request, 'courses/course-list.html', {
#         'all_courses': all_courses,
#         'recommend_courses': recommend_courses,
#         'pages': pages,
#         'sort': sort,
#         'keyword': keyword
#     })


class CourseDetailView(View):
    def get(self, request, course_id):
        print(fr"course_detail:{course_id}")
        if course_id:
            course = CourseInfo.objects.filter(id=int(course_id))[0]
            course.click_num += 1
            course.save()

            course_love_status = get_love_status(request, course_id, 2)
            org_love_status = get_love_status(request, course.org_info.id, 1)

            # 相关课程
            relate_courses = CourseInfo.objects.filter(category=course.category) \
                                 .exclude(id=int(course_id))[:2]

            return render(request, 'courses/course-detail.html', {
                'course': course,
                'course_love_status': course_love_status,
                'org_love_status': org_love_status,
                'relate_courses': relate_courses
            })


# def course_detail(request, course_id):
#     print(fr"course_detail:{course_id}")
#     if course_id:
#         course = CourseInfo.objects.filter(id=int(course_id))[0]
#         course.click_num += 1
#         course.save()
#
#         course_love_status = get_love_status(request, course_id, 2)
#         org_love_status = get_love_status(request, course.org_info.id, 1)
#
#         # 相关课程
#         relate_courses = CourseInfo.objects.filter(category=course.category) \
#                              .exclude(id=int(course_id))[:2]
#
#         return render(request, 'courses/course-detail.html', {
#             'course': course,
#             'course_love_status': course_love_status,
#             'org_love_status': org_love_status,
#             'relate_courses': relate_courses
#         })

class CourseVideoView(View):
    @login_decorators
    def get(self, request, course_id):
        if course_id:
            course = CourseInfo.objects.filter(id=int(course_id))[0]
            # 开始学习
            user_course_list = UserCourseInfo.objects.filter(study_man=request.user, study_course=course)
            if not user_course_list:
                user_course = UserCourseInfo()
                user_course.study_man = request.user
                user_course.study_course = course
                user_course.save()
                # 第一次学习 时候加+1 课程
                course.study_num += 1
                course.save()
                course.org_info.study_num += 1
                course.org_info.save()

            return render(request, 'courses/course-video.html', {
                'course': course,
                'course_list': get_study_course_list(course)
            })


# @login_required(login_url='/users/user_login')
# @login_decorators
# def course_video(request, course_id):
#     if course_id:
#         course = CourseInfo.objects.filter(id=int(course_id))[0]
#         # 开始学习
#         user_course_list = UserCourseInfo.objects.filter(study_man=request.user, study_course=course)
#         if not user_course_list:
#             user_course = UserCourseInfo()
#             user_course.study_man = request.user
#             user_course.study_course = course
#             user_course.save()
#             # 第一次学习 时候加+1 课程
#             course.study_num += 1
#             course.save()
#             course.org_info.study_num += 1
#             course.org_info.save()
#
#         return render(request, 'courses/course-video.html', {
#             'course': course,
#             'course_list': get_study_course_list(course)
#         })

class CourseCommentView(View):
    def get(self, request, course_id):
        if course_id:
            course = CourseInfo.objects.filter(id=int(course_id))[0]
            user_comment_course_list = UserCommentInfo.objects.filter(comment_course_id=course.id)[:10]
            return render(request, 'courses/course-comment.html', {
                'course': course,
                'course_list': get_study_course_list(course),
                'user_comment_course_list': user_comment_course_list
            })


# def course_comment(request, course_id):
#     if course_id:
#         course = CourseInfo.objects.filter(id=int(course_id))[0]
#         user_comment_course_list = UserCommentInfo.objects.filter(comment_course_id=course.id)[:10]
#         return render(request, 'courses/course-comment.html', {
#             'course': course,
#             'course_list': get_study_course_list(course),
#             'user_comment_course_list': user_comment_course_list
#         })


def get_study_course_list(course):
    # 学过改课的同学还学过什么课程
    user_course_list = UserCourseInfo.objects.filter(study_course=course)
    # 找到素有的用户的列表 列表生成式
    user_list = [u.study_man for u in user_course_list]
    user_course_list = UserCourseInfo.objects.filter(study_man__in=user_list) \
        .exclude(id=int(course.id))
    # 取课程去重
    return list(set([c.study_course for c in user_course_list]))[:2]

templates/courses/course-comment.html
{% extends 'base.html' %}

{# 加载静态文件 #}
{% load static %}

{% block title %}
    公开课评论
{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/course/learn-less.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/course/course-comment.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/common-less.css' %}/">
    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/course/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}"/>
{% endblock %}


{% block content %}

    <section>
        <div class="wp">
            <div class="crumbs">
                <ul>
                    <li><a href="{% url 'index' %}">首页</a>></li>
                    <li><a href="{% url 'courses:course_list' %}">公开课程</a>></li>
                    <li><a href="{% url 'courses:course_detail' course.id %}">课程详情</a>></li>
                    <li>课程评论</li>
                </ul>
            </div>
        </div>
    </section>

    <div id="main">
        <div class="course-infos">
            <div class="w pr">
                <div style="height: 15px" class="path">
                </div>
                <div class="hd">
                    <h2 class="l" style="position: absolute;left: 10px">{{ course.name }}</h2>
                </div>
                <div class="statics clearfix">
                    <div class="static-item " style="bottom: -10px">
                        <span class="meta-value">
                            <strong>
                                {% if recommend_course.level == 'cj' %} 初级
                                {% elif recommend_course.level == 'zj' %} 中级
                                {% else %} 高级
                                {% endif %}
                            </strong>
                        </span>
                        <span class="meta">难度</span>
                        <em></em>
                    </div>
                    <div class="static-item static-time" style="bottom: -10px">
                        <span class="meta-value">
                            <strong>
                                {{ course.study_time }}分钟
                            </strong>
                        </span>
                        <span class="meta">时长</span>
                        <em></em>
                    </div>
                    <div class="static-item" style="bottom: -10px">
                        <span class="meta-value"><strong>{{ course.study_num }}</strong></span>
                        <span class="meta">学习人数</span>
                        <em></em>
                    </div>
                </div>
            </div>
        </div>

        <div class="course-info-main clearfix w has-progress">

            <div class="info-bar clearfix">
                <div class="content-wrap clearfix">
                    <div class="content">
                        <div class="mod-tab-menu">
                            <ul class="course-menu clearfix">
                                <li><a class="ui-tabs-active " id="learnOn"
                                       href="{% url 'courses:course_video' course.id %}"><span>章节</span></a>
                                </li>
                                <li><a id="commentOn" class="active"
                                       href="{% url 'courses:course_comment' course.id %}"><span>评论</span></a>
                                </li>
                            </ul>
                        </div>

                        <!--发布评论-->
                        <div id="js-pub-container" class="issques clearfix js-form">
                            <div class="wgt-ipt-wrap pub-editor-wrap " id="js-pl-input-fake">
                            <textarea id="js-pl-textarea" class=""
                                      placeholder="扯淡、吐槽、表扬、鼓励……想说啥就说啥！"></textarea>
                            </div>
                            <input type="button" id="js-pl-submit" class="pub-btn" data-cid="452" value="发表评论">
                            <p class="global-errortip js-global-error"></p>
                        </div>

                        <div id="course_note">
                            <ul class="mod-post" id="comment-list">

                                {% for comment in user_comment_course_list %}
                                    <li class="post-row">
                                        <div class="media">
                                    <span target="_blank">
                                        <img src='{{ MEDIA_URL }}{{ comment.comment_man.image }}' width='40'
                                             height='40' alt="{{ comment.comment_man.username }}"/>
                                    </span>
                                        </div>
                                        <div class="bd">
                                            <div class="tit">
                                                <span target="_blank">{{ comment.comment_man.username }}</span>
                                            </div>
                                            <p class="cnt">{{ comment.comment_content }}</p>
                                            <div class="footer clearfix">
                                                <span title="创建时间" class="l timeago">{{ comment.add_time }}</span>
                                            </div>
                                        </div>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>

                    <div class="aside r">
                        <div class="bd">

                            <div class="box mb40">
                                <h4>资料下载</h4>
                                <ul class="downlist">

                                    {% for source in course.sourceinfo_set.all %}
                                        <li>
                                            <span><i
                                                    class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ source.name }}</span>
                                            <a href="{{ MEDIA_URL }}{{ source.down_load }}" class="downcode"
                                               target="_blank" download="" data-id="274" title="">下载</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="box mb40">
                                <h4>讲师提示</h4>
                                <div class="teacher-info">
                                    <a href="{% url 'orgs:teacher_detail' course.teacher_info.id %}" target="_blank">
                                        <img src='{{ MEDIA_URL }}{{ course.teacher_info.image }}' width='80'
                                             height='80' alt="{{ course.teacher_info.name }}"/>
                                    </a>
                                    <span class="tit">
                                        <a href="{% url 'orgs:teacher_detail' course.teacher_info.id %}"
                                           target="_blank">
                                            {{ course.teacher_info.name }}
                                        </a>
                                    </span>
                                    <span class="job">
                                        {{ course.teacher_info.work_position }}
                                    </span>
                                </div>
                                <div class="course-info-tip">
                                    <dl class="first">
                                        <dt>课程须知</dt>
                                        <dd class="autowrap">{{ course.course_need }}</dd>
                                    </dl>
                                    <dl>
                                        <dt>老师告诉你能学到什么？</dt>
                                        <dd class="autowrap">{{ course.teacher_tell }}</dd>
                                    </dl>
                                </div>
                            </div>


                            <div class="cp-other-learned  js-comp-tabs">
                                <div class="cp-header clearfix">
                                    <h2 class="cp-tit l">该课的同学还学过</h2>
                                </div>
                                <div class="cp-body">
                                    <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course"
                                         style="display: block">
                                        <!-- img 200 x 112 -->
                                        <ul class="other-list">
                                            {% for cou in course_list %}
                                                <li class="curr">
                                                    <a href="{% url 'courses:course_detail' cou.id %}" target="_blank">
                                                        <img src="{{ MEDIA_URL }}{{ cou.image }}" alt="{{ cou.name }}">
                                                        <span class="name autowrap">{{ cou.name }}</span>
                                                    </a>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </div>

                                </div>
                            </div>

                        </div>
                    </div>

                </div>

                <div class="clear">


                </div>

            </div>

        </div>
    </div>

{% endblock %}


{% block js %}

    <script>
        $(function () {
            $('#js-pl-submit').click(function () {
                let comment = $('#js-pl-textarea').val();
                $.ajax({
                    type: 'POST',
                    url: '{% url 'operations:user_comment' %}',
                    data: {
                        {# 课程/人/内容  #}
                        {#comment_man:{{ request.user }},#}
                        comment_course:{{ course.id }},
                        comment_content: comment,
                        csrfmiddlewaretoken: '{{ csrf_token }}'
                    },
                    success: function (callback) {
                        if (callback.status === 200) {
                            {#页面刷新 纯前端#}
                            {#$('#js-pl-textarea').val('');#}
                            window.location.reload();
                        } else if (callback.status === 403) {
                            window.location.href = '{% url 'users:user_login' %}'
                        } else {
                            alert(callback.msg)
                        }
                    }
                })
            })
        })
    </script>

{% endblock %}