Django_/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Django_ import settings
from users.views import IndexView

urlpatterns = [
                  # 首页直接进行跳转
                  path('', IndexView.as_view(), name='index'),
                  path('admin/', admin.site.urls),
                  path('captcha/', include('captcha.urls')),
                  path('ckeditor/', include('ckeditor_uploader.urls')),
                  # version more better I have last version
                  # path('ueditor/', include('DjangoUeditor.urls')),
                  # path('xadmin/', xadmin.site.urls),
                  path('users/', include(('users.urls', 'users'), namespace='users')),
                  path('courses/', include(('courses.urls', 'courses'), namespace='courses')),
                  path('orgs/', include(('orgs.urls', 'orgs'), namespace='orgs')),
                  path('operations/', include(('operations.urls', 'operations'), namespace='operations')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'users.views.handle_404'
handler500 = 'users.views.handler_500'

apps/courses/urls.py
from django.urls import path, re_path

from .views import CourseListView, CourseDetailView, CourseVideoView, CourseCommentView

urlpatterns = [
    path('course_list/', CourseListView.as_view(), name='course_list'),
    re_path('course_detail/(\\d+)', CourseDetailView.as_view(), name='course_detail'),
    re_path('course_video/(\\d+)', CourseVideoView.as_view(), name='course_video'),
    re_path('course_comment/(\\d+)', CourseCommentView.as_view(), name='course_comment'),
]

apps/operations/urls.py
from django.urls import path

from .views import UserAskView, UserLoveView, UserDeleteLoveView, UserCommentView, UserMessageView

urlpatterns = [
    path('user_ask/', UserAskView.as_view(), name='user_ask'),

    path('user_love/', UserLoveView.as_view(), name='user_love'),
    path('user_delete_love/', UserDeleteLoveView.as_view(), name='user_delete_love'),

    path('user_comment/', UserCommentView.as_view(), name='user_comment'),
    path('user_message/', UserMessageView.as_view(), name='user_message'),
]

apps/orgs/urls.py
from django.urls import path, re_path

from .views import OrgListView, OrgDetailView, OrgDetailCourseView, OrgDetailDescView, OrgDetailTeachersView, \
    TeacherListView, TeacherDetailView

urlpatterns = [
    path('org_list/', OrgListView.as_view(), name='org_list'),
    re_path('org_detail/(\\d+)', OrgDetailView.as_view(), name='org_detail'),
    re_path('org_detail_course/(\\d+)', OrgDetailCourseView.as_view(), name='org_detail_course'),
    re_path('org_detail_desc/(\\d+)', OrgDetailDescView.as_view(), name='org_detail_desc'),
    re_path('org_detail_teachers/(\\d+)', OrgDetailTeachersView.as_view(), name='org_detail_teachers'),
    # teacher
    path('teacher_list/', TeacherListView.as_view(), name='teacher_list'),
    re_path('teacher_detail/(\\d+)', TeacherDetailView.as_view(), name='teacher_detail'),
]

apps/users/urls.py
from django.urls import path, re_path

from .views import UserRegisterView, UserLoginView, UserLogoutView, UserActiveView, UserForgetView, UserResetView, \
    UserInfoView, UserChangeImageView, UserChangeInfoView, UserChangeEmailView, UserRestEmailView, UserCourseView, \
    UserLoveOrgView, UserLoveCourseView, UserLoveTeacherView, UserMessageView

urlpatterns = [
    # name 必须是 'xxx'
    path('user_register/', UserRegisterView.as_view(), name='user_register'),
    path('user_login/', UserLoginView.as_view(), name='user_login'),
    path('user_logout/', UserLogoutView.as_view(), name='user_logout'),
    # 如果要使用正则表达式 需要使用re_path
    re_path('user_active/(\\w+)/', UserActiveView.as_view(), name='user_active'),

    path('user_forget/', UserForgetView.as_view(), name='user_forget'),
    re_path('user_reset/(\\w+)/', UserResetView.as_view(), name='user_reset'),

    path('user_info/', UserInfoView.as_view(), name='user_info'),
    path('user_change_image/', UserChangeImageView.as_view(), name='user_change_image'),
    path('user_change_info/', UserChangeInfoView.as_view(), name='user_change_info'),
    path('user_change_email/', UserChangeEmailView.as_view(), name='user_change_email'),
    path('user_rest_email/', UserRestEmailView.as_view(), name='user_rest_email'),

    path('user_course/', UserCourseView.as_view(), name='user_course'),
    path('user_love_org/', UserLoveOrgView.as_view(), name='user_love_org'),
    path('user_love_teacher/', UserLoveTeacherView.as_view(), name='user_love_teacher'),
    path('user_love_course/', UserLoveCourseView.as_view(), name='user_love_course'),

    path('user_message/', UserMessageView.as_view(), name='user_message'),
]

apps/courses/models.py
from datetime import datetime

from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models

from orgs.models import OrgInfo, TeacherInfo


# Create your models here.
class CourseInfo(models.Model):
    image = models.ImageField(upload_to='course/', verbose_name='课程封面', max_length=200)
    name = models.CharField(max_length=20, verbose_name='课程名称')
    is_banner = models.BooleanField(default=False, verbose_name='是否轮播')

    study_time = models.IntegerField(default=0, verbose_name='学习时长')
    study_num = models.IntegerField(default=0, verbose_name='学习人数')
    level = models.CharField(choices=(('gj', '高级'), ('zj', '中级'), ('cj', '初级')), default='cj', max_length=3,
                             verbose_name='难度')

    love_num = models.IntegerField(default=0, verbose_name='收藏数')
    click_num = models.IntegerField(default=0, verbose_name='访问量')

    desc = models.CharField(verbose_name='课程简介', max_length=200)
    # detail = models.TextField(verbose_name='课程详情')
    detail = RichTextUploadingField(default='', verbose_name='课程详情')

    category = models.CharField(choices=(('qd', '前端开发'), ('hd', '后端开发')), default='hd',
                                verbose_name='课程类别', max_length=20)

    course_notice = models.CharField(max_length=200, verbose_name='课程公告')
    course_need = models.CharField(max_length=200, verbose_name='课程须知')
    teacher_tell = models.CharField(max_length=200, verbose_name='老师告诉')
    org_info = models.ForeignKey(OrgInfo, verbose_name='所属机构', on_delete=models.CASCADE)
    teacher_info = models.ForeignKey(TeacherInfo, verbose_name='所属讲师', on_delete=models.CASCADE)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '课程信息'
        verbose_name_plural = verbose_name


# 章节信息
class ChapterInfo(models.Model):
    name = models.CharField(max_length=20, verbose_name='章节名称')
    course_info = models.ForeignKey(CourseInfo, verbose_name='所属课程', on_delete=models.CASCADE)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '章节信息'
        verbose_name_plural = verbose_name


class VideoInfo(models.Model):
    name = models.CharField(max_length=20, verbose_name='视频名称')
    study_time = models.IntegerField(default=0, verbose_name='视频时长')
    url = models.URLField(default='https://www.baidu.com', verbose_name='视频链接', max_length=200)
    chapter_info = models.ForeignKey(ChapterInfo, verbose_name='所属章节', on_delete=models.CASCADE)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '视频信息'
        verbose_name_plural = verbose_name


class SourceInfo(models.Model):
    name = models.CharField(max_length=20, verbose_name='资源名称')
    down_load = models.FileField(upload_to='source/', verbose_name='下载路径', max_length=200)
    course_info = models.ForeignKey(CourseInfo, verbose_name='所属课程', on_delete=models.CASCADE)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '资源信息'
        verbose_name_plural = verbose_name

apps/users/models.py
from datetime import datetime

from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class UserProfile(AbstractUser):
    # 补充字段
    image = models.ImageField(upload_to='user/', max_length=200, verbose_name='用户头像', null=True, blank=True)
    nick_name = models.CharField(max_length=20, verbose_name='用户名称', null=True, blank=True)
    birthday = models.DateField(verbose_name='用户生日', null=True, blank=True)
    gender = models.CharField(choices=(('girl', '女'), ('boy', '男')), max_length=10, verbose_name='用户性别',
                              default='gril')
    address = models.CharField(max_length=200, verbose_name='用户地址', null=True, blank=True)
    phone = models.CharField(max_length=11, verbose_name='用户手机', null=True, blank=True)
    status = models.BooleanField(default=False, verbose_name='是否激活')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.username

    def get_message_count(self):
        from operations.models import UserMessageInfo
        return UserMessageInfo.objects.filter(message_status=False, message_man=self.id).count()

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name


class BannerInfo(models.Model):
    # 补充字段
    image = models.ImageField(upload_to='banner/', max_length=200, verbose_name='轮播图片')
    url = models.URLField(default='https://www.baidu.com', max_length=200, verbose_name='图片链接')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return str(self.image)

    class Meta:
        verbose_name = '轮播图信息'
        verbose_name_plural = verbose_name


class EmailVerifyCode(models.Model):
    # 补充字段
    code = models.CharField(max_length=20, verbose_name='邮箱验证码')
    email = models.EmailField(max_length=200, verbose_name='验证码邮箱')
    # 1 注册  2 重置密码  3 修改邮箱
    send_type = models.IntegerField(choices=((1, 'register'), (2, 'forget'), (3, 'change')), default=1,
                                    verbose_name='验证码类型')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = '邮箱验证码'
        verbose_name_plural = verbose_name

apps/users/forms.py
from captcha.fields import CaptchaField
from django import forms

from .models import UserProfile, EmailVerifyCode


class UserRegisterForm(forms.Form):
    # 自动校验
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True, min_length=3, max_length=20, error_messages={
        'required': '密码必须填写',
        'min_length': '密码至少3位',
        'max_length': '密码最多20位',
    })
    # 验证码
    captcha = CaptchaField()


class UserLoginForm(forms.Form):
    # 自动校验
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True, min_length=3, max_length=20, error_messages={
        'required': '密码必须填写',
        'min_length': '密码至少3位',
        'max_length': '密码最多20位',
    })


class UserForgetForm(forms.Form):
    # 自动校验
    email = forms.EmailField(required=True)
    # 验证码
    captcha = CaptchaField()


class UserResetForm(forms.Form):
    # 自动校验
    password = forms.CharField(required=True, min_length=3, max_length=20, error_messages={
        'required': '密码必须填写',
        'min_length': '密码至少3位',
        'max_length': '密码最多20位',
    })
    password1 = forms.CharField(required=True, min_length=3, max_length=20, error_messages={
        'required': '密码必须填写',
        'min_length': '密码至少3位',
        'max_length': '密码最多20位',
    })


class UserChangeImageForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['image']


class UserChangeInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['nick_name', 'gender', 'birthday', 'address', 'phone']


class UserChangeEmailForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['email']


class UserRestEmailForm(forms.ModelForm):
    class Meta:
        model = EmailVerifyCode
        fields = ['email', 'code']

templates/users/user_base.html
{% extends 'base.html' %}

{# 加载静态文件 #}
{% load static %}

{% block css %}

    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/lq.datetimepick.css' %}"/>

{% endblock %}


{% block middle %}

    <div class="middle">
        <div class="wp">
            <a href="/">
                <img class="fl" src="{% static 'images/logo1.png' %}"/>
            </a>
            <h1>我的爱时尚教育网</h1>
        </div>
    </div>

{% endblock %}

{% block content %}

    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="/">首页</a>></li>
                <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
                <li>{% block breach %}{% endblock %}</li>
            </ul>
        </div>
    </section>

    <section>
        <div class="wp list personal_list">
            <div class="left">
                <ul>
                    <li {% if request.path == '/users/user_info/' %}class="active2" {% endif %}>
                        <a href="{% url 'users:user_info' %}">个人资料</a>
                    </li>
                    <li {% if request.path == '/users/user_course/' %}class="active2" {% endif %}>
                        <a href="{% url 'users:user_course' %}">我的课程</a>
                    </li>
                    <li {% if request.resolver_match.url_name == 'user_love_org' or request.resolver_match.url_name == 'user_love_teacher' or request.resolver_match.url_name == 'user_love_course' %}
                        class="active2" {% endif %}>
                        <a href="{% url 'users:user_love_org' %}">我的收藏</a>
                    </li>
                    <li {% if request.path == '/users/user_message/' %}class="active2" {% endif %}>
                        <a href="{% url 'users:user_message' %}" style="position: relative;">
                            我的消息
                        </a>
                    </li>
                </ul>
            </div>

            {% block right %} {% endblock %}

        </div>
    </section>

    {% block dialog %}
        <div class="dialog" id="jsDialog">
            <div class="resetpwdbox dialogbox" id="jsResetDialog">
                <h1>修改密码</h1>
                <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
                <div class="cont">
                    <form id="jsResetPwdForm" autocomplete="off">
                        <div class="box">
                            <span class="word2">新&nbsp;&nbsp;密&nbsp;&nbsp;码</span>
                            <input type="password" id="pwd" name="password1" placeholder="6-20位非中文字符"/>
                        </div>
                        <div class="box">
                            <span class="word2">确定密码</span>
                            <input type="password" id="repwd" name="password2" placeholder="6-20位非中文字符"/>
                        </div>
                        <div class="error btns" id="jsResetPwdTips"></div>
                        <div class="button">
                            <input id="jsResetPwdBtn" type="button" value="提交"/>
                        </div>
                        <input type='hidden' name='csrfmiddlewaretoken' value='DaP7IUKm9FA9nELA9YUlYYWpyIDdCiIP'/>
                        <input type='hidden' name='csrfmiddlewaretoken' value='799Y6iPeEDNSGvrTu3noBrO4MBLv6enY'/>
                    </form>
                </div>
            </div>
            <div class="dialogbox changeemai1 changephone" id="jsChangeEmailDialog">
                <h1>修改邮箱</h1>
                <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
                <p>请输入新的邮箱地址</p>
                <form id="jsChangeEmailForm" autocomplete="off">
                    <div class="box">
                        <input class="fl change_email" name="email" id="jsChangeEmail" type="text"
                               placeholder="输入重新绑定的邮箱地址">
                    </div>
                    <div class="box">
                        <input class="fl email_code" type="text" id="jsChangeEmailCode" name="code"
                               placeholder="输入邮箱验证码">
                        <input class="getcode getting" type="button" id="jsChangeEmailCodeButton" value="获取验证码">
                    </div>
                    <div class="error btns change_email_tips" id="jsChangeEmailTips">请输入...</div>
                    <div class="button">
                        <input class="changeemai_btn" id="jsChangeEmailButton" type="button" value="完成"/>
                    </div>
                    <input type='hidden' name='csrfmiddlewaretoken' value='DaP7IUKm9FA9nELA9YUlYYWpyIDdCiIP'/>
                    <input type='hidden' name='csrfmiddlewaretoken' value='799Y6iPeEDNSGvrTu3noBrO4MBLv6enY'/>
                </form>
            </div>
        </div>

        <div class="bg" id="dialogBg"></div>
    {% endblock %}
{% endblock %}

{% block footer %} {% endblock %}

{% block js %}
    <script src='{% static 'js/plugins/jquery.upload.js' %}' type='text/javascript'></script>
    <script src="{% static 'js/validate.js' %}" type="text/javascript"></script>
    <script>
        $(function () {
            $('#jsChangeEmailCodeButton').click(function () {
                let email = $('#jsChangeEmail').val()
                $.ajax({
                    type: 'POST',
                    url: '{% url 'users:user_change_email' %}',
                    data: {
                        email: email,
                        csrfmiddlewaretoken: '{{ csrf_token }}'
                    },
                    success: function (callback) {
                        alert(callback.msg)
                    }
                })
            })
        })
    </script>
    <script>
        $(function () {
            $('#jsChangeEmailButton').click(function () {
                $.ajax({
                    type: 'POST',
                    url: '{% url 'users:user_rest_email' %}',
                    data: {
                        email: $('#jsChangeEmail').val(),
                        code: $('jsChangeEmailCode').val(),
                        csrfmiddlewaretoken: '{{ csrf_token }}'
                    },
                    success: function (callback) {
                        if (callback.status === 200) {
                            alert(callback.msg)
                            {# 跳转登陆页面  #}
                            window.location.href = '{% url 'users:user_login' %}'
                        } else {
                            alert(callback.msg)
                        }
                    }
                })
            })
        })
    </script>
    {% block js1 %} {% endblock %}
{% endblock %}

templates/users/usercenter-fav-course.html
{% extends 'users/user_base.html' %}

{% load static %}

{% block title %}
    我的收藏
{% endblock %}

{% block breach %}
    我的收藏
{% endblock %}

{% block right %}
    <div class="right">
        <div class="personal_des Releasecont">
            <div class="head">
                <h1>我的收藏</h1>
            </div>
        </div>
        <div class="personal_des permessage">

            <div class="head">
                <ul class="tab_header messagehead">
                    <li {% if request.path == '/users/user_love_org/' %} class="active" {% endif %}>
                        <a href="{% url 'users:user_love_org' %}">课程机构</a>
                    </li>
                    <li {% if request.path == '/users/user_love_teacher/' %} class="active" {% endif %}>
                        <a href="{% url 'users:user_love_teacher' %}">授课教师 </a>
                    </li>
                    <li {% if request.path == '/users/user_love_course/' %} class="active" {% endif %}>
                        <a href="{% url 'users:user_love_course' %}">公开课程</a>
                    </li>
                </ul>
            </div>

            <div class="companycenter">
                <div class="group_list brief">

                    {% for course in courses %}
                        <div class="module1_5 box">
                            <a href="{% url 'courses:course_detail' course.id %}">
                                <img width="214" height="190" src="{{ MEDIA_URL }}{{ course.image }}"
                                     alt="{{ course.name }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'courses:course_detail' course.id %}"><h2>{{ course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ course.study_time }}</i></span>
                                <span class="fr">学习人数：{{ course.study_num }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.org_info.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ course.id }}"></span>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block dialog %} {% endblock %}

{% block js1 %}
    <script>
        {#  删除收藏  #}
        $(function () {
            $('.delete-group').click(function () {
                {# attr 自定义属性 prop 元素自带的值 #}
                let course_id = $(this).attr('data-favid')
                let obj = $(this)
                $.ajax({
                    type: 'GET',
                    url: '{% url 'operations:user_delete_love' %}',
                    data: {
                        love_id: course_id,
                        love_type: 2
                    },
                    success: function (callback) {
                        if (callback.status === 200) {
                            alert(callback.msg)
                            {#window.location.reload()#}
                            obj.parents('.module1_5').remove()
                        } else if (callback.status === 403) {
                            window.location.href = '{% url 'users:user_login' %}'
                        } else {
                            alert(callback.msg)
                        }
                    }
                })
            })
        })

    </script>
{% endblock %}

templates/users/usercenter-fav-org.html
{% extends 'users/user_base.html' %}

{% load static %}

{% block title %}
    我的收藏
{% endblock %}

{% block breach %}
    我的收藏
{% endblock %}

{% block right %}
    <div class="right">
        <div class="personal_des Releasecont">
            <div class="head">
                <h1>我的收藏</h1>
            </div>

        </div>
        <div class="personal_des permessage">
            <div class="head">
                <ul class="tab_header messagehead">
                    <li {% if request.path == '/users/user_love_org/' %} class="active" {% endif %}>
                        <a href="{% url 'users:user_love_org' %}">课程机构</a>
                    </li>
                    <li {% if request.path == '/users/user_love_teacher/' %} class="active" {% endif %}>
                        <a href="{% url 'users:user_love_teacher' %}">授课教师 </a>
                    </li>
                    <li {% if request.path == '/users/user_love_course/' %} class="active" {% endif %}>
                        <a href="{% url 'users:user_love_course' %}">公开课程</a>
                    </li>
                </ul>
            </div>

            <div class="messagelist">

                <div class="messages butler_list company company-fav-box">

                    {% for org in orgs %}

                        <dl class="des fr">
                            <dt>
                                <a href="{% url 'orgs:org_detail' org.id %}">
                                    <img width="160" height="90" src="{{ MEDIA_URL }}{{ org.image }}"
                                         alt="{{ org.name }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1><a href="{% url 'orgs:org_detail' org.id %}">{{ org.name }}</a></h1>
                                <div class="pic fl" style="width:auto;">

                                    <img src="{% static 'images/authentication.png' %}" alt="认证"/>

                                    <img src="{% static 'images/gold.png' %}" alt="金牌"/>

                                </div>
                                <span class="c8 clear">{{ org.address }}</span>

                                <div class="delete jsDeleteFav_org" data-favid="{{ org.id }}"></div>
                            </dd>
                        </dl>

                    {% endfor %}
                </div>

            </div>
        </div>
    </div>
{% endblock %}

{% block dialog %} {% endblock %}

{% block js1 %}
    <script>
        {#  删除收藏  #}
        $(function () {
            $('.delete').click(function () {
                {# attr 自定义属性 prop 元素自带的值 #}
                let org_id = $(this).attr('data-favid')
                let obj = $(this)
                $.ajax({
                    type: 'GET',
                    url: '{% url 'operations:user_delete_love' %}',
                    data: {
                        love_id: org_id,
                        love_type: 1
                    },
                    success: function (callback) {
                        if (callback.status === 200) {
                            alert(callback.msg)
                            {#window.location.reload()#}
                            obj.parents('.des').remove()
                        } else if (callback.status === 403) {
                            window.location.href = '{% url 'users:user_login' %}'
                        } else {
                            alert(callback.msg)
                        }
                    }
                })
            })
        })

    </script>
{% endblock %}

templates/users/usercenter-fav-teacher.html
{% extends 'users/user_base.html' %}

{% load static %}

{% block title %}
    我的收藏
{% endblock %}

{% block breach %}
    我的收藏
{% endblock %}

{% block right %}
    <div class="right">
        <div class="personal_des Releasecont">
            <div class="head">
                <h1>我的收藏</h1>
            </div>
        </div>
        <div class="personal_des permessage">

            <div class="head">
                <ul class="tab_header messagehead">
                    <li {% if request.path == '/users/user_love_org/' %} class="active" {% endif %}>
                        <a href="{% url 'users:user_love_org' %}">课程机构</a>
                    </li>
                    <li {% if request.path == '/users/user_love_teacher/' %} class="active" {% endif %}>
                        <a href="{% url 'users:user_love_teacher' %}">授课教师 </a>
                    </li>
                    <li {% if request.path == '/users/user_love_course/' %} class="active" {% endif %}>
                        <a href="{% url 'users:user_love_course' %}">公开课程</a>
                    </li>
                </ul>
            </div>

            <div class="messagelist">

                <div class=" butler_list butler-fav-box">
                    {% for teacher in teachers %}
                        <dl class="des users">
                            <dt>
                                <a href="{% url 'orgs:teacher_detail' teacher.id %}">
                                    <img width="100" height="100" src="{{ MEDIA_URL }}{{ teacher.image }}"
                                         alt="{{ teacher.name }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1>
                                    <a href="{% url 'orgs:teacher_detail' teacher.id %}">
                                        {{ teacher.name }}<span class="key">认证教师</span>
                                    </a>
                                </h1>
                                <ul class="cont clearfix">
                                    <li class="time">工作年限：<span>{{ teacher.work_year }}</span></li>
                                    <li class="c7">课程数：<span>{{ teacher.courseinfo_set.count }}</span></li>
                                </ul>
                                <ul class="cont clearfix">
                                    <li class="time">工作公司：<span>{{ teacher.work_company.name }}</span></li>
                                    <li class="c7">公司职位：<span>{{ teacher.work_position }}</span></li>
                                </ul>
                            </dd>
                            <div class="delete jsDeleteFav_teacher" data-favid="{{ teacher.id }}"></div>
                        </dl>
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block dialog %} {% endblock %}

{% block js1 %}
    <script>
        {#  删除收藏  #}
        $(function () {
            $('.delete').click(function () {
                {# attr 自定义属性 prop 元素自带的值 #}
                let teacher_id = $(this).attr('data-favid')
                let obj = $(this)
                $.ajax({
                    type: 'GET',
                    url: '{% url 'operations:user_delete_love' %}',
                    data: {
                        love_id: teacher_id,
                        love_type: 3
                    },
                    success: function (callback) {
                        if (callback.status === 200) {
                            alert(callback.msg)
                            {#window.location.reload()#}
                            obj.parents('.des').remove()
                        } else if (callback.status === 403) {
                            window.location.href = '{% url 'users:user_login' %}'
                        } else {
                            alert(callback.msg)
                        }
                    }
                })
            })
        })

    </script>
{% endblock %}